/**
 * Real-World E2E QA — Browser UI Verification
 *
 * Reads .qa-context.json (generated by scripts/e2e-qa/run-qa.ts) and
 * verifies every role's UI pages against real data created by the API layer.
 *
 * Usage:
 *   npx playwright test e2e/qa-realworld.spec.ts --project=chromium --no-deps
 *
 * Prerequisite: npx tsx scripts/e2e-qa/run-qa.ts (must pass first)
 */

import { test, expect, Page } from "@playwright/test";
import * as fs from "fs";
import * as path from "path";

// ---------------------------------------------------------------------------
// Load QA context from API layer
// ---------------------------------------------------------------------------
const CONTEXT_PATH = path.join(__dirname, "../scripts/e2e-qa/.qa-context.json");

interface QAContext {
  superAdminToken: string;
  superAdminUserId: string;
  adminToken: string;
  adminUserId: string;
  dispatcherToken: string;
  dispatcherUserId: string;
  shipperToken: string;
  shipperUserId: string;
  shipperOrgId: string;
  carrierToken: string;
  carrierUserId: string;
  carrierOrgId: string;
  truckId: string;
  truckPostingId: string;
  gpsDeviceId: string;
  loadId: string;
  load2Id: string;
  tripId: string;
  trip2Id: string;
  truckRequestId: string;
  addisLocationId: string;
  credentials: Record<string, { email: string; password: string }>;
}

let ctx: QAContext;

test.beforeAll(() => {
  if (!fs.existsSync(CONTEXT_PATH)) {
    throw new Error(
      `QA context not found at ${CONTEXT_PATH}. Run "npx tsx scripts/e2e-qa/run-qa.ts" first.`
    );
  }
  ctx = JSON.parse(fs.readFileSync(CONTEXT_PATH, "utf-8"));
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const ROLE_PORTALS: Record<string, string> = {
  superadmin: "/admin",
  admin: "/admin",
  dispatcher: "/dispatcher",
  shipper: "/shipper",
  carrier: "/carrier",
};

/** Log in via the UI using the redirect param to ensure correct portal */
async function uiLogin(
  page: Page,
  role: string,
  email: string,
  password: string
) {
  const portal = ROLE_PORTALS[role] || "/";
  await page.goto(`/login?redirect=${portal}`);
  await page.getByLabel("Email address").fill(email);
  await page.getByLabel("Password").fill(password);
  await page.getByRole("button", { name: /sign in/i }).click();
  // Wait for navigation away from /login
  await page.waitForURL((url) => !url.pathname.startsWith("/login"), {
    timeout: 15000,
  });
}

/** Get visible rendered text from the page (not RSC payloads) */
async function pageText(page: Page): Promise<string> {
  return page.innerText("body");
}

/** Assert page loaded without server errors */
async function assertNoErrorPage(page: Page) {
  const text = await pageText(page);
  expect(text).not.toContain("500 Internal Server Error");
  expect(text).not.toContain("Application error");
}

/** Navigate and wait for page to be interactive */
async function goTo(page: Page, url: string) {
  await page.goto(url);
  await page.waitForLoadState("domcontentloaded");
  // Give client components time to hydrate
  await page.waitForTimeout(2000);
}

// ---------------------------------------------------------------------------
// B1 — Super Admin UI
// ---------------------------------------------------------------------------
test.describe.serial("B1 — Super Admin UI", () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    await uiLogin(
      page,
      "superadmin",
      ctx.credentials.superadmin.email,
      ctx.credentials.superadmin.password
    );
  });

  test.afterAll(async () => {
    await page.close();
  });

  test("B1.1: Login redirects to /admin", async () => {
    expect(page.url()).toContain("/admin");
  });

  test("B1.2: Admin users list shows Abebe Girma", async () => {
    await goTo(page, "/admin/users");
    await assertNoErrorPage(page);
    await expect(page.getByText("Abebe")).toBeVisible({ timeout: 10000 });
  });

  test("B1.3: Audit logs page loads", async () => {
    await goTo(page, "/admin/audit-logs");
    await assertNoErrorPage(page);
  });

  test("B1.4: Create Admin form exists (SUPER_ADMIN only)", async () => {
    await goTo(page, "/admin/users/create");
    await assertNoErrorPage(page);
    const text = await pageText(page);
    expect(
      text.includes("Create") ||
        text.includes("Email") ||
        text.includes("email")
    ).toBeTruthy();
  });
});

// ---------------------------------------------------------------------------
// B2 — Admin UI
// ---------------------------------------------------------------------------
test.describe.serial("B2 — Admin UI", () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    await uiLogin(
      page,
      "admin",
      ctx.credentials.admin.email,
      ctx.credentials.admin.password
    );
  });

  test.afterAll(async () => {
    await page.close();
  });

  test("B2.1: Login redirects to /admin", async () => {
    expect(page.url()).toContain("/admin");
  });

  test("B2.2: User list loads", async () => {
    await goTo(page, "/admin/users");
    await assertNoErrorPage(page);
    const text = await pageText(page);
    expect(text).toContain("shipper@addisfreight.et");
  });

  test("B2.3: No Create Admin link for ADMIN role", async () => {
    await goTo(page, "/admin/users/create");
    // API blocks it — just verify no crash
    await assertNoErrorPage(page);
  });

  test("B2.4: Wallets page loads", async () => {
    await goTo(page, "/admin/wallets");
    await assertNoErrorPage(page);
  });
});

// ---------------------------------------------------------------------------
// B3 — Shipper UI
// ---------------------------------------------------------------------------
test.describe.serial("B3 — Shipper UI", () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    await uiLogin(
      page,
      "shipper",
      ctx.credentials.shipper.email,
      ctx.credentials.shipper.password
    );
  });

  test.afterAll(async () => {
    await page.close();
  });

  test("B3.1: Login redirects to /shipper", async () => {
    expect(page.url()).toContain("/shipper");
  });

  test("B3.2: Wallet page shows balance and transactions", async () => {
    await goTo(page, "/shipper/wallet");
    await assertNoErrorPage(page);
    const text = await pageText(page);
    expect(text.includes("Balance") || text.includes("ETB")).toBeTruthy();
  });

  test("B3.3: Loads page shows assigned load", async () => {
    await goTo(page, "/shipper/loads");
    await assertNoErrorPage(page);
    const text = await pageText(page);
    expect(
      text.includes("ASSIGNED") ||
        text.includes("COMPLETED") ||
        text.includes("Dire Dawa")
    ).toBeTruthy();
  });

  test("B3.4: Loadboard page loads", async () => {
    await goTo(page, "/shipper/loadboard");
    await assertNoErrorPage(page);
  });

  test("B3.5: Trips page shows trip data", async () => {
    await goTo(page, "/shipper/trips");
    await assertNoErrorPage(page);
    const text = await pageText(page);
    expect(
      text.includes("COMPLETED") ||
        text.includes("Dire Dawa") ||
        text.includes("Trip")
    ).toBeTruthy();
  });
});

// ---------------------------------------------------------------------------
// B4 — Carrier UI
// ---------------------------------------------------------------------------
test.describe.serial("B4 — Carrier UI", () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    await uiLogin(
      page,
      "carrier",
      ctx.credentials.carrier.email,
      ctx.credentials.carrier.password
    );
  });

  test.afterAll(async () => {
    await page.close();
  });

  test("B4.1: Login redirects to carrier portal", async () => {
    expect(page.url()).toContain("/carrier");
  });

  test("B4.2: Trucks page shows ET-AA-12345 with APPROVED", async () => {
    await goTo(page, "/carrier/trucks");
    await assertNoErrorPage(page);
    await expect(page.getByRole("table").getByText("ET-AA-12345")).toBeVisible({
      timeout: 10000,
    });
  });

  test("B4.3: Loadboard page loads", async () => {
    await goTo(page, "/carrier/loadboard");
    await assertNoErrorPage(page);
  });

  test("B4.4: Wallet shows balance and fee deduction", async () => {
    await goTo(page, "/carrier/wallet");
    await assertNoErrorPage(page);
    const text = await pageText(page);
    expect(
      text.includes("SERVICE_FEE") ||
        text.includes("Service Fee") ||
        text.includes("Fee") ||
        text.includes("fee")
    ).toBeTruthy();
  });

  test("B4.5: Trip history shows completed trip", async () => {
    await goTo(page, "/carrier/trip-history");
    await assertNoErrorPage(page);
    const text = await pageText(page);
    expect(
      text.includes("Completed") || text.includes("COMPLETED")
    ).toBeTruthy();
  });
});

// ---------------------------------------------------------------------------
// B5 — Dispatcher UI
// ---------------------------------------------------------------------------
test.describe.serial("B5 — Dispatcher UI", () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    await uiLogin(
      page,
      "dispatcher",
      ctx.credentials.dispatcher.email,
      ctx.credentials.dispatcher.password
    );
  });

  test.afterAll(async () => {
    await page.close();
  });

  test("B5.1: Login redirects to dispatcher", async () => {
    expect(page.url()).toContain("/dispatcher");
  });

  test("B5.2: Dashboard stat cards load", async () => {
    await goTo(page, "/dispatcher/dashboard");
    await assertNoErrorPage(page);
    const text = await pageText(page);
    expect(
      text.includes("Dashboard") || text.includes("dashboard")
    ).toBeTruthy();
  });

  test("B5.3: Trips list loads", async () => {
    await goTo(page, "/dispatcher/trips");
    await assertNoErrorPage(page);
  });

  test("B5.4: Trucks list loads", async () => {
    await goTo(page, "/dispatcher/trucks");
    await assertNoErrorPage(page);
  });

  test("B5.5: Truck detail page loads", async () => {
    if (!ctx.truckId) {
      test.skip();
      return;
    }
    await goTo(page, `/dispatcher/trucks/${ctx.truckId}`);
    await assertNoErrorPage(page);
    const text = await pageText(page);
    expect(text).toContain("ET-AA-12345");
  });

  test("B5.6: Escalations page loads", async () => {
    await goTo(page, "/dispatcher/escalations");
    await assertNoErrorPage(page);
  });
});

// ---------------------------------------------------------------------------
// B6 — Admin Analytics & Wallets
// ---------------------------------------------------------------------------
test.describe.serial("B6 — Admin Analytics & Wallets", () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    await uiLogin(
      page,
      "admin",
      ctx.credentials.admin.email,
      ctx.credentials.admin.password
    );
  });

  test.afterAll(async () => {
    await page.close();
  });

  test("B6.1: Analytics page shows revenue metrics", async () => {
    await goTo(page, "/admin/analytics");
    await assertNoErrorPage(page);
    const text = await pageText(page);
    expect(
      text.includes("Revenue") ||
        text.includes("revenue") ||
        text.includes("ETB") ||
        text.includes("Fee")
    ).toBeTruthy();
  });

  test("B6.2: Analytics shows load count", async () => {
    const text = await pageText(page);
    expect(
      text.includes("Load") ||
        text.includes("load") ||
        text.includes("Trip") ||
        text.includes("trip")
    ).toBeTruthy();
  });

  test("B6.3: Wallets page shows wallet data", async () => {
    await goTo(page, "/admin/wallets");
    await assertNoErrorPage(page);
    const text = await pageText(page);
    expect(
      text.includes("Addis Freight") ||
        text.includes("Tigray Transport") ||
        text.includes("Wallet") ||
        text.includes("wallet") ||
        text.includes("Balance")
    ).toBeTruthy();
  });
});

// ---------------------------------------------------------------------------
// B7 — Edge Case UI Tests
// ---------------------------------------------------------------------------
test.describe.serial("B7 — Edge Case UI Tests", () => {
  test("B7.1: Document lock — shipper upload is locked", async ({
    browser,
  }) => {
    const page = await browser.newPage();
    await uiLogin(
      page,
      "shipper",
      ctx.credentials.shipper.email,
      ctx.credentials.shipper.password
    );
    await goTo(page, "/shipper/documents");
    await assertNoErrorPage(page);
    const text = await pageText(page);
    expect(
      text.toLowerCase().includes("locked") ||
        text.toLowerCase().includes("approved") ||
        text.toLowerCase().includes("cannot upload") ||
        text.toLowerCase().includes("verified")
    ).toBeTruthy();
    await page.close();
  });

  test("B7.2: Role routing — shipper cannot access /carrier/trucks", async ({
    browser,
  }) => {
    const page = await browser.newPage();
    await uiLogin(
      page,
      "shipper",
      ctx.credentials.shipper.email,
      ctx.credentials.shipper.password
    );
    await page.goto("/carrier/trucks");
    await page.waitForLoadState("domcontentloaded");
    await page.waitForTimeout(3000);

    const url = page.url();
    const text = await pageText(page);
    expect(
      url.includes("unauthorized") ||
        url.includes("login") ||
        text.includes("Unauthorized") ||
        text.includes("Access Denied") ||
        text.includes("not authorized")
    ).toBeTruthy();
    await page.close();
  });

  test("B7.3: Notification bell — carrier page loads", async ({ browser }) => {
    const page = await browser.newPage();
    await uiLogin(
      page,
      "carrier",
      ctx.credentials.carrier.email,
      ctx.credentials.carrier.password
    );
    await goTo(page, "/carrier/dashboard");
    await assertNoErrorPage(page);
    // Page loads without errors — notification bell is a visual element
    const text = await pageText(page);
    expect(text).toBeTruthy();
    await page.close();
  });
});
