/* eslint-disable @typescript-eslint/no-require-imports */
/**
 * FINAL MERGED AUDIT
 *
 * Joins Test 1 (DB+API) and Test 2 (DB+Web+Expo) into one combined table:
 *
 *   Role | User | Metric | Page | DB | API | Web | Expo | Result
 *
 * Inputs (must be regenerated by running the two audits first):
 *   /tmp/audit-test1.json   ← scripts/audit-test1-api.ts
 *   /tmp/audit-test2.json   ← scripts/audit-test2-ui.ts
 *
 * Cross-validates that the DB value for the same metric matches between
 * Test 1 and Test 2 (DB drift would indicate the test order or seed
 * mutated state). Marks rows that are present in only one test with the
 * other surface as "n/a (no API endpoint)" or "n/a (no UI page)" with an
 * explicit reason — never as a silent skip.
 */

const fs = require("fs");

interface T1Row {
  role: string;
  user: string;
  metric: string;
  db: number | string | null;
  api: number | string | null;
  note?: string;
}

interface T2Row {
  role: string;
  user: string;
  metric: string;
  page: string;
  db: number | string | null;
  web: number | string | null;
  expo: number | string | null;
}

interface MergedRow {
  role: string;
  user: string;
  metric: string;
  page: string;
  db: string;
  api: string;
  web: string;
  expo: string;
  reason?: string;
}

const t1: T1Row[] = JSON.parse(
  fs.readFileSync("/tmp/audit-test1.json", "utf-8")
);
const t2: T2Row[] = JSON.parse(
  fs.readFileSync("/tmp/audit-test2.json", "utf-8")
);

// ─── Canonical metric name mapping ──────────────────────────────────────────
//
// Test 1 and Test 2 use slightly different metric names for the same concept
// (Test 2 uses lowercase URL tab names like "loads_posted"; Test 1 uses
// uppercase enum names like "loads_POSTED"). The merge needs a canonical
// name so the join works.

function canon(role: string, metric: string): string {
  // Shipper loads tabs → enum names
  const shipperLoadTabMap: Record<string, string> = {
    loads_draft: "loads_DRAFT",
    loads_unposted: "loads_UNPOSTED",
    loads_posted: "loads_POSTED",
    loads_delivered: "loads_DELIVERED",
    loads_completed: "loads_COMPLETED",
    loads_cancelled: "loads_CANCELLED",
    loads_exception: "loads_EXCEPTION",
    loads_expired: "loads_EXPIRED",
    // loads_active = ASSIGNED+PICKUP_PENDING+IN_TRANSIT — multi-status, no
    // direct equivalent in Test 1's per-status check; merge as its own metric
    loads_active: "loads_active_tab",
  };
  // Carrier trips tabs
  const carrierTripTabMap: Record<string, string> = {
    trips_approved_tab: "trips_ASSIGNED",
    // active tab = PICKUP_PENDING+IN_TRANSIT+DELIVERED+EXCEPTION; merged
    // as its own composite metric
    trips_active_tab: "trips_active_composite_tab",
  };
  // Carrier truck status enum names already match (trucks_APPROVED, etc.)
  // Shipper trips_DELIVERED etc. already match.
  // Admin metrics: dash_total_users vs total_users, etc.
  const adminMap: Record<string, string> = {
    dash_total_users: "total_users",
    analytics_users: "total_users",
    admin_users_total: "total_users",
    dash_total_orgs: "total_organizations",
    analytics_orgs: "total_organizations",
    admin_orgs_total: "total_organizations",
    dash_total_loads: "total_loads",
    analytics_loads: "total_loads",
    admin_loads_total: "total_loads",
    dash_total_trucks: "total_trucks",
    analytics_trucks: "total_trucks",
    admin_trucks_total: "total_trucks",
    admin_trips_total: "total_trips",
    admin_wallets_total: "admin_wallet_account_count",
    admin_withdrawals_pending: "pending_withdrawals_count",
  };
  if (role === "Shipper") {
    if (shipperLoadTabMap[metric]) return shipperLoadTabMap[metric];
    if (metric === "dashboard_total_loads") return "loads_total";
  }
  if (role === "Carrier") {
    if (carrierTripTabMap[metric]) return carrierTripTabMap[metric];
    if (metric === "dashboard_total_trucks") return "trucks_total";
  }
  if (role === "Admin" || role === "Super Admin") {
    if (adminMap[metric]) return adminMap[metric];
  }
  return metric;
}

// Build keyed lookups
const t1Map = new Map<string, T1Row>();
for (const r of t1) {
  const key = `${r.role}|${r.user}|${canon(r.role, r.metric)}`;
  // Prefer the first one if there are multiple (canon mappings collapse
  // dash/analytics/admin into the same metric name). Verify they agree.
  const existing = t1Map.get(key);
  if (existing) {
    if (String(existing.db) !== String(r.db)) {
      console.warn(`[merge] T1 DB drift on ${key}: ${existing.db} vs ${r.db}`);
    }
  } else {
    t1Map.set(key, r);
  }
}

const t2Map = new Map<string, T2Row>();
for (const r of t2) {
  const key = `${r.role}|${r.user}|${canon(r.role, r.metric)}`;
  const existing = t2Map.get(key);
  if (existing) {
    if (String(existing.db) !== String(r.db)) {
      console.warn(`[merge] T2 DB drift on ${key}: ${existing.db} vs ${r.db}`);
    }
  } else {
    t2Map.set(key, r);
  }
}

// Union of all keys
const allKeys = new Set<string>([...t1Map.keys(), ...t2Map.keys()]);

const merged: MergedRow[] = [];
const dbDrifts: string[] = [];

for (const key of allKeys) {
  const [role, user, metric] = key.split("|");
  const r1 = t1Map.get(key);
  const r2 = t2Map.get(key);

  // Cross-test DB drift check
  if (r1 && r2 && String(r1.db) !== String(r2.db)) {
    dbDrifts.push(`${role} ${user} ${metric}: T1.db=${r1.db} T2.db=${r2.db}`);
  }

  const dbVal = r1?.db ?? r2?.db ?? null;
  const apiVal = r1?.api;
  const webVal = r2?.web;
  const expoVal = r2?.expo;

  let reason = "";
  let api = "n/a (no API endpoint for this metric)";
  let web = "n/a (no UI page for this metric)";
  let expo = "n/a (no Expo screen for this metric)";

  if (apiVal !== undefined) api = String(apiVal);
  if (webVal !== undefined && webVal !== null && webVal !== "-")
    web = String(webVal);
  if (webVal === "-") web = "n/a (no UI page for this metric)";
  if (expoVal !== undefined && expoVal !== null && expoVal !== "-")
    expo = String(expoVal);
  if (expoVal === "-") expo = "n/a (no Expo screen — gap)";

  // If the metric is exclusively in T1, mark Web/Expo as n/a-no-page
  if (r1 && !r2) {
    web = "n/a (no UI page tested)";
    expo = "n/a (no Expo screen tested)";
    reason = "API-only (no corresponding UI/Expo coverage)";
  }
  // If exclusively in T2, mark API as n/a
  if (r2 && !r1) {
    api = "n/a (no API endpoint covered in Test 1)";
    reason = "UI-only (Test 2 stand-alone)";
  }

  merged.push({
    role,
    user,
    metric,
    page: r2?.page || "—",
    db: String(dbVal),
    api,
    web,
    expo,
    reason,
  });
}

// ─── Result calculation ─────────────────────────────────────────────────────
function isNa(v: string): boolean {
  return v.startsWith("n/a");
}
function passOf(r: MergedRow): "✅" | "❌" | "⚠️" {
  // Drift in any populated cell vs DB = ❌
  for (const v of [r.api, r.web, r.expo]) {
    if (!isNa(v) && v !== r.db) return "❌";
  }
  // If any column is "no Expo screen — gap" → partial (⚠️)
  if (r.expo.includes("gap")) return "⚠️";
  return "✅";
}

// ─── Sort and print ─────────────────────────────────────────────────────────
const roleOrder: Record<string, number> = {
  Shipper: 0,
  Carrier: 1,
  Dispatcher: 2,
  Admin: 3,
  "Super Admin": 4,
};
merged.sort((a, b) => {
  const r = (roleOrder[a.role] ?? 9) - (roleOrder[b.role] ?? 9);
  if (r !== 0) return r;
  if (a.user !== b.user) return a.user.localeCompare(b.user);
  return a.metric.localeCompare(b.metric);
});

const cols = ["Role", "User", "Metric", "DB", "API", "Web", "Expo", "Result"];
const widths = cols.map((c) => c.length);
const data = merged.map((r) => [
  r.role,
  r.user,
  r.metric,
  r.db,
  r.api,
  r.web,
  r.expo,
  passOf(r),
]);
for (const row of data) {
  row.forEach((c, i) => {
    if (c.length > widths[i]) widths[i] = c.length;
  });
}
const fr = (cells: string[]) =>
  cells.map((c, i) => c.padEnd(widths[i])).join("  ");

console.log("\n=== FINAL MERGED AUDIT TABLE ===\n");
console.log(fr(cols));
console.log(widths.map((w) => "-".repeat(w)).join("  "));
for (const row of data) console.log(fr(row));

// ─── Summary ────────────────────────────────────────────────────────────────
const fullPass = merged.filter((r) => passOf(r) === "✅").length;
const partial = merged.filter((r) => passOf(r) === "⚠️").length;
const fails = merged.filter((r) => passOf(r) === "❌");

const fullyVerified = merged.filter(
  (r) => !isNa(r.api) && !isNa(r.web) && !isNa(r.expo) && passOf(r) === "✅"
);
const partialExpoGap = merged.filter(
  (r) => r.expo.includes("gap") && passOf(r) !== "❌"
);
const apiOnly = merged.filter(
  (r) => !isNa(r.api) && isNa(r.web) && isNa(r.expo)
);
const uiOnly = merged.filter((r) => isNa(r.api) && !isNa(r.web));

console.log("\n=== SUMMARY ===");
console.log(`Total merged metrics: ${merged.length}`);
console.log(`  ✅ Pass (db = every populated cell): ${fullPass}`);
console.log(`  ⚠️  Partial (Expo gap, no drift): ${partial}`);
console.log(`  ❌ Fail: ${fails.length}`);
console.log("");
console.log(
  `Fully verified across all 4 surfaces (DB+API+Web+Expo): ${fullyVerified.length}`
);
console.log(
  `Partially verified (Expo screen not yet tested):       ${partialExpoGap.length}`
);
console.log(
  `API-only (no UI page exists or not tested):            ${apiOnly.length}`
);
console.log(
  `UI-only (no API endpoint covered in Test 1):           ${uiOnly.length}`
);

if (dbDrifts.length > 0) {
  console.log("\n=== DB DRIFT BETWEEN TESTS (would be a real bug) ===");
  for (const d of dbDrifts) console.log(`  ${d}`);
} else {
  console.log(
    "\nDB drift between Test 1 and Test 2: NONE — every shared metric agrees."
  );
}

if (fails.length > 0) {
  console.log("\n=== FAILURES ===");
  for (const f of fails) {
    console.log(
      `  ❌ ${f.role} ${f.user} ${f.metric}: db=${f.db} api=${f.api} web=${f.web} expo=${f.expo}`
    );
  }
  process.exit(1);
}

console.log("\nZero failures confirmed.");
